### ISSUE TITLE
Final Stuff

### ISSUE THREAD

**Issue by Dezainer** [SelflessDev/psico#22]
**Part 1**
- [x] Articles: 1-Frases, 2-Artigos, 3-Contato
- [x] Old "Articles" links
- [x] Footer little spelling errors
- [x] Change Card Names to Articles
- [x] Contact - Mini Personal Description
- [x] Create Something to Separate "Articles" from "Frases" (they are together in the Cards)
- [x] Home Arrow Scroll
- [x] Menu Icon kind of 'bad to click'
- [x] Home Links sizes kind of wrong...
- [x] Footer Center Alignment

**Part 2**
- [x] Nome da frase do topo -> Orientação Psicológica
- [x] Por Link na frase da home pro institucional
- [x] Mudar o nome do menu de escritos para artigos
- [x] Tirar Mini-Curriculo do Contato e por telefones pra cima
- [ ] Phone on Top of Home
